image: node:latest

cache:
  paths:
    - viz/node_modules/
    - server/node_modules/
    - scene/node_modules/

before_script:
  - cd viz && yarn install
  - cd server && yarn install
  - cd scene && yarn install

pages:
  stage: deploy
  script:
  - cd viz
  - yarn build
  - mv build ../public
  artifacts:
    paths:
      - public
  only:
  - master
